"""
天書奇談 - 跨 k=0..9 全局排名表預計算
位元遮罩 + 對稱壓縮加速
輸出 rank_tables.js (給前端離線查表用)
"""
import time
from itertools import combinations
from collections import Counter
import json

# ─── 線的位元遮罩(16-bit) ───
LINES_MASK = []
for r in range(4):
    LINES_MASK.append(sum(1 << (r*4+c) for c in range(4)))  # 橫
for c in range(4):
    LINES_MASK.append(sum(1 << (r*4+c) for r in range(4)))  # 直
LINES_MASK.append(sum(1 << i for i in (0,5,10,15)))
LINES_MASK.append(sum(1 << i for i in (3,6,9,12)))

def count_lines_bm(bitmask):
    """位元遮罩:超快線檢查"""
    n = 0
    for lm in LINES_MASK:
        if (bitmask & lm) == lm:
            n += 1
    return n

def precompute_rank_table(k):
    """
    對所有 C(16,k) 種 k 貼紙配置,枚舉剩下 (9-k) 格的所有放法
    回傳:每個目標 (=0,1,2,3 / ≥1, ≥2, ≥3) 的機率分佈
    """
    if k > 9:
        return None
    n_remaining = 9 - k
    if k < 0 or n_remaining < 0:
        return None
    
    all_cells = list(range(16))
    
    # 統計每個配置在剩餘格隨機填後的線數分佈
    # ge1_counter[p_numerator] = number of configs with that probability
    ge_counters = {1: Counter(), 2: Counter(), 3: Counter()}
    exact_counters = {0: Counter(), 1: Counter(), 2: Counter(), 3: Counter()}
    
    if n_remaining == 0:
        # k=9: 每個配置決定論
        total_per_config = 1
    else:
        # C(16-k, 9-k)
        from math import comb
        total_per_config = comb(16-k, 9-k)
    
    total_configs = 0
    for placed in combinations(all_cells, k):
        bm_placed = sum(1 << c for c in placed)
        empty = [c for c in all_cells if not (bm_placed >> c) & 1]
        
        cnt_lines = Counter()
        if n_remaining == 0:
            cnt_lines[count_lines_bm(bm_placed)] = 1
        else:
            for combo in combinations(empty, n_remaining):
                bm_full = bm_placed
                for c in combo:
                    bm_full |= (1 << c)
                cnt_lines[count_lines_bm(bm_full)] += 1
        
        # 計算機率 (用 numerator 表示,避免浮點誤差)
        for target in [1, 2, 3]:
            num = sum(c for nl, c in cnt_lines.items() if nl >= target)
            ge_counters[target][num] += 1
        for exact in [0, 1, 2, 3]:
            num = cnt_lines.get(exact, 0)
            exact_counters[exact][num] += 1
        total_configs += 1
    
    return {
        'k': k,
        'total_configs': total_configs,
        'denominator': total_per_config,
        'ge': {tgt: dict(ge_counters[tgt]) for tgt in [1,2,3]},
        'exact': {ex: dict(exact_counters[ex]) for ex in [0,1,2,3]},
    }

# ─── 對 k=0..9 全部跑 ───
print(f"開始預計算 k=0..9 ...")
all_tables = {}
total_start = time.time()
for k in range(0, 10):
    t0 = time.time()
    table = precompute_rank_table(k)
    elapsed = time.time() - t0
    n_tiers_ge3 = len(table['ge'][3])
    n_tiers_ge2 = len(table['ge'][2])
    n_tiers_ge1 = len(table['ge'][1])
    print(f"  k={k}: configs={table['total_configs']:>5}, denom={table['denominator']:>6}, "
          f"tiers(≥1/≥2/≥3)={n_tiers_ge1}/{n_tiers_ge2}/{n_tiers_ge3}  [{elapsed:.2f}s]")
    all_tables[k] = table
total_elapsed = time.time() - total_start
print(f"全部完成,總耗時 {total_elapsed:.2f}s")

# ─── 輸出總結表 ───
print()
print("="*78)
print("各 k 的「P(≥3 線)」分佈摘要(排序)")
print("="*78)
for k in range(0, 10):
    t = all_tables[k]
    denom = t['denominator']
    print(f"\n● k={k}  (總 {t['total_configs']} 配置,分母 {denom})")
    for num in sorted(t['ge'][3].keys(), reverse=True):
        cnt = t['ge'][3][num]
        pct_prob = num/denom*100 if denom else 0
        pct_configs = cnt/t['total_configs']*100
        print(f"    P(≥3)={num:>5}/{denom:<5} = {pct_prob:>7.4f}%  →  {cnt:>5} 配置 ({pct_configs:>6.3f}%)")

# ─── 輸出 JS 常數 ───
print()
print("="*78)
print("產出 JS 常數 → rank_tables.js")
print("="*78)

js_tables = {}
for k in range(0, 10):
    t = all_tables[k]
    denom = t['denominator']
    
    # 三個目標(≥1, ≥2, ≥3)各一張表,按 numerator 降序
    def make_tier_list(counter_dict):
        items = sorted(counter_dict.items(), key=lambda x: -x[0])
        return [{"n": num, "c": cnt} for num, cnt in items]
    
    js_tables[str(k)] = {
        "total": t['total_configs'],
        "denom": denom,
        "ge1": make_tier_list(t['ge'][1]),
        "ge2": make_tier_list(t['ge'][2]),
        "ge3": make_tier_list(t['ge'][3]),
    }

# 緊湊 JSON
js_content = "/* AUTO-GENERATED by gen_rank_table.py — DO NOT EDIT */\n"
js_content += "const RANK_TABLES = " + json.dumps(js_tables, separators=(',', ':')) + ";\n"

out_path = "/sessions/inspiring-vigilant-knuth/mnt/outputs/rank_tables.js"
with open(out_path, "w") as f:
    f.write(js_content)

import os
size = os.path.getsize(out_path)
print(f"已寫入 {out_path}")
print(f"檔案大小: {size} bytes ({size/1024:.2f} KB)")
print()
print("驗證:k=7 的 P(≥3) 分佈應為 [{3:16}, {2:8}, {1:800}, {0:10616}]")
print(f"實際: {js_tables['7']['ge3']}")
